# yaml-language-server: $schema=https://json.schemastore.org/nuejs-site.json

globals: ["@global"]
libs: ["@library"]

view_transitions: true
native_css_nesting: true
inline_css: true
sections: true

title_template: "Ctrl + Rems / %s"
og_image: /img/og_rems.png
author: Rems
favicon: /img/favicon.jpg
description: ⌨️ Collection of keyboard shortcuts I use every day
port: 8083

# OG image
origin: https://simple-blog.nuejs.org
og: /img/og.jpg


navigation:
  header:
    - Rems: /
    - Contact: /contact/

  footer:
    - © Rems: /

    - image: /img/github.svg
      url: //github.com/remirobichet
      alt: Github Projects
      size: 22 x 22
